export const IMAGE_SAVE_REQUEST = 'IMAGE_SAVE_REQUEST'
export const IMAGE_SAVE_SUCCESS = 'IMAGE_SAVE_SUCCESS'
export const IMAGE_SAVE_FAIL = 'IMAGE_SAVE_FAIL'

export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS'
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL'

