export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS'
export const PRODUCT_LIST_FAIL = 'PRODUCT_LIST_FAIL'

export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST'
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS'
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL'

export const PRODUCT_ITEM_REQUEST = 'PRODUCT_ITEM_REQUEST'
export const PRODUCT_ITEM_SUCCESS = 'PRODUCT_ITEM_SUCCESS'
export const PRODUCT_ITEM_FAIL = 'PRODUCT_ITEM_FAIL'

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST'
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS'
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL'

export const PAYMENT_UPDATED_SUCCESS = 'PAYMENT_UPDATED_SUCCESS'
export const PAYMENT_UPDATED_FAIL = 'PAYMENT_UPDATED_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'